### ISSUE TITLE
Google Maps and Height

### ISSUE THREAD

**Issue by danieldocki** [bbarakaci/fixto#11]
This example in #gruboo-map element if you put a value of 800px in min-height stopped working the sticky. 

http://jsfiddle.net/vL2hr/1/

That just does not happen in Safari because it has native support, but does not work in chrome, firefox etc. ...

**Comment by bbarakaci** [comment]
I am really sorry not being able to pull this. At the end i implemented it, similar to yours. I took advantage of the case for a little bit refactoring on the related area. I used a different option name, i don't remember why. Excuse me for not adding your contribution to the repository.
