### ISSUE TITLE
CSS Doesn't Reset on .destroy()

### ISSUE THREAD

**Issue by gdvine** [bbarakaci/fixto#21]
fixto adds inline styles to the target element, but these styles are not removed on .destroy(). For resize events where fixto must be disabled and reenabled based on various widths, this causes havoc with the layout.

**Comment by bbarakaci** [comment]
It saves the original inline style values right before fixing and resets the original values when unfixed, stopped or destroyed. So, no added inline style should remain on the element. You can check it on this simple page: http://bbarakaci.github.io/fixto/dev3.html

If you could provide an example that behaves differently i could check it out.
