### ISSUE TITLE
Not Working on iPad

### ISSUE THREAD

**Issue by AreYouAWizard** [bbarakaci/fixto#22]
Hello,

I tested this on an ipad and a galaxy tab and it doesn't work, do you know any fix ?

Thank you.

**Comment by bbarakaci** [comment]
Update it if you are using an old version. Earlier versions did not supported touch devices.

Please try testing the links provided on the homepage. They seem to work for me.

**Comment by AreYouAWizard** [comment]
Thank you very much

Have a nice day

**Comment by bbarakaci** [comment]
Thank you. You too.
