### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by ejb** [bbarakaci/fixto#25]
This is a wonderful bit of software. It would be even better with a formal license, to clarify where it's ok to use. For example, can it be included in paid-for software? Etc.

GitHub have a [useful site](http://choosealicense.com) explaining the advantages of each. I would recommend the MIT license.

**Comment by bbarakaci** [comment]
Right now it has yet unofficial JUID license  (Just Use It Dude)

I will switch to MIT license as soon as possible. Thanks.

**Comment by rafegoldberg** [comment]
hahah big fan of the "JUID" license (and this plugin in general)

**Comment by bbarakaci** [comment]
MIT license added with the latest release. Sorry for the delay.

**Comment by ejb** [comment]
Hooray! Thanks!
