### ISSUE TITLE
Does not unstick in Microsoft Edge

### ISSUE THREAD

**Issue by Coruin** [bbarakaci/fixto#26]
The plugin appears to work only particially: After scrolling downwards and reaching the top of the viewport, it gets sticky. When you scroll up again, it won't unstick.

However, Firefox works fine. It seems like it is only broken with that new Microsoft browser :)

before scroll down/up:
![before scroll down/up](https://cloud.githubusercontent.com/assets/13752163/9204422/88ac7b48-405d-11e5-8d66-1806b2dd30ec.jpg)

after scroll down/up:
![after scroll down/up](https://cloud.githubusercontent.com/assets/13752163/9204436/928ce472-405d-11e5-9557-45fa2e435a78.jpg)

**Comment by patrickkettner** [comment]
The [same thing is happening in chrome](http://naturstammhaus-freystein.de/)

**Comment by bbarakaci** [comment]
header#branding's computed height is 0. Because all of its children are out of the flow. Floats has to be cleared. Giving header#branding overflow: auto will do it. You can select the most convenient method for you to clear the floats.
