### ISSUE TITLE
Firefox 44.0.1

### ISSUE THREAD

**Issue by saracen7** [bbarakaci/fixto#34]
Updated Firefox to version 44.0.1 today on MS WIndows 10 and native positioning no longer seems to work. Anyone else seen this?

**Comment by WarGravy** [comment]
+1 - yes, I have run into this exact problem with 44.0.2

**Comment by bbarakaci** [comment]
demo pages seems to work fine, and using native position sticky. i checked it on os x and windows 10 with 44.0.2

**Comment by saracen7** [comment]
Yup. Checking 0n 0.2 it seems to have been fixed. Thanks Mozilla for making me look crazy! :) 
WarGravy, maybe you shoud open up an issue for yourself to see what else is causing you the problems, because sticky definitely seems to be back in 0.2

**Comment by WarGravy** [comment]
Strange I didn't think there would be a difference in OS so I didn't bother providing the details. I'm running windows 7 enterprise, Firefox 44.0.2, and here is the sample js:

```
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="prebuilt/js/fixto.min.js"></script>

    <script>
      $('#fixed-nav').fixTo('body');
    </script>
```

And here is the html element further down in the page:

```
<nav id="fixed-nav"></nav>

#fixed-nav{
height:100px;
background-color:#000;
display:block;
margin:0;
padding:0;
border:0;
vertical-align:baseline;
text-align:left;
}
```

Once it applies the position: sticky and the top: 0 (which it does) nothing else seems to happen nor work. The moment I change the useNativeSticky option to false it works again.

```
$('#fixed-nav').fixTo('body', {
            useNativeSticky: false
        });
```

**Comment by WarGravy** [comment]
I didn't think it would be OS related, I'm running Windows 7 enterprise and that might be the problem with Firefox and win7

**Comment by saracen7** [comment]
Definitely works with the code you had earlier on Windows 10. So it may be OS related. Have you tried it on a wrapper container rather than the body? The only other option otherwise other than a false native sticky is to fallback to css fixed positioning

**Comment by WarGravy** [comment]
Hmmm yeah, I just tried using different wrappers and run into the same problem. Disabling the native sticky positioning seems to work just fine though and will have to do. Thank you for verifying that code in windows 10 for me! I appreciate it.

**Comment by saracen7** [comment]
Not a problem. Happy to help.
