### ISSUE TITLE
Stick to bottom when element is taller

### ISSUE THREAD

**Issue by djmtype** [bbarakaci/fixto#37]
If the element to be stuck fits within the viewport, fixto works. If taller, fixto doesn't get applied for accessibility reasons. Ok, that makes sense. 
But, why not provide an option of sticking the element to the bottom of the parent container when it's taller than the viewport height?

I've also tried applying `viewportHeight: true` or `viewportHeight: false` to options. Neither made a difference.

**Comment by Wardee-IDUK** [comment]
+1 for this

**Comment by Lospepes** [comment]
We have the same problem !

**Comment by southwails** [comment]
Firefox native sticky (presumably w3c compliant) allows element to be higher than the viewport, so it would be good to have this at least as an option.

**Comment by bbarakaci** [comment]
Apparently it was an opinionated feature as many complained about it. I pushed a new version. Now it is not enabled by default. I think sticking to bottom also clips the content from top so i doubt it worths the effort. I will close this issue as won't fix. Hopefully not having the feature will be sufficient for most.
