### ISSUE TITLE
Get/list all fixTo instances?

### ISSUE THREAD

**Issue by rafegoldberg** [bbarakaci/fixto#38]
Is there a way to get all of the `fixTo` jQuery plugin instances that are active on the current page?

**Comment by bbarakaci** [comment]
No such feature but give this one a try. It should return all the elements that has an attached instance.

```
$('*').filter(function() {
    return $(this).data("fixto-instance") !== undefined 
});
```

**Comment by rafegoldberg** [comment]
thanks man, I hadn't considered doing it this way; will give it a spin! (The `*` selector always gives me pause re: performance. I'd probably use something like `$( [class*="fix"] )` instead. Though now that I think about it I actually have no idea if attribute selectors are actually any faster...)

**Comment by bbarakaci** [comment]
Yes. It is not performance friendly.

Class names are applied only when it is fixed as far as I can remember. So
you can query the proper class name if it is your intention.
