### ISSUE TITLE
Does not work on Firefox

### ISSUE THREAD

**Issue by pratikchaskar** [bbarakaci/fixto#41]
This JS is perfectly working on chrome but having issues with FireFox. 

1. Stick class is not applying
2. By default there is some CSS applied - http://bsf.io/xgnwd

**Comment by bbarakaci** [comment]
Which version of Firefox?

Could you check the development pages linked on the read me section with
the same browser to see if examples works properly.

Class will not be applied when native positive sticky is used. You can try
to disable native sticky usage. See how to do, on read me section.

**Comment by pratikchaskar** [comment]
Hey! Thanks for your help.

I have used useNativeSticky to false & it works perfectly!

http://bsf.io/b2vop
