### ISSUE TITLE
Fixto disables scrolling on latest Chrome (Windows Only)

### ISSUE THREAD

**Issue by nicklovelyday** [bbarakaci/fixto#52]
Somehow, when I visit my website with Chrome 61.0.3163.91 on Windows 10, I can't scroll (with my mouse scroll wheel) after fixto is loaded. When I disable fixto, scrolling works again. Tried the version 0.3.0 and 0.5.0 but same problem.

I don't have this problem on any other browser on Windows, and also not on Chrome on Mac.

Disabled Chrome extensions and tried in Incognito. 

My domain is: https://3dscanexpert.com/

Any ideas?

**Comment by bbarakaci** [comment]
Hello,

I checked it in a virtual machine, with trackpad (didn't have mouse wheel) and i was not able to reproduce. Chrome 61.0.3163.100 on windows.

**Comment by nicklovelyday** [comment]
I found the solution.

After removing this code from another script on my website, scrolling
worked again:

if ( ! $('body').hasClass('osx') ) { // disable for mac 			
     $('body').smoothScroll(); 		
}


So that might interfere with fixto.
